#!/usr/bin/env bash

set -e

workstation_repo_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -x /usr/local/bin/bundle ]
then
  sudo gem install bundler -v '< 2'
fi

pushd "${workstation_repo_dir}"
  bundle install --binstubs --path vendor/bundle --without development
  bin/soloist
popd

